"""Shared helpers for the marathon dashboard scripts."""

import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(ROOT, "data")
CONFIG_PATH = os.path.join(ROOT, "config.json")
ACTIVITIES_PATH = os.path.join(DATA_DIR, "activities.json")
PLAN_PATH = os.path.join(DATA_DIR, "training_plan.json")
DATA_JS_PATH = os.path.join(DATA_DIR, "data.js")
SEED_CSV = os.path.join(DATA_DIR, "_seed", "activities.csv")
STRAVA_STATE_PATH = os.path.join(DATA_DIR, "strava_state.json")

METERS_PER_MILE = 1609.34
FEET_PER_METER = 3.28084


def load_config():
    """Credentials come from env vars in the cloud (GitHub Actions), else config.json locally.

    In cloud mode the rotating refresh_token is persisted to data/strava_state.json (committed
    to the private repo) so the next scheduled run picks up the latest one.
    """
    env_id = os.environ.get("STRAVA_CLIENT_ID")
    if env_id:
        state = {}
        if os.path.exists(STRAVA_STATE_PATH):
            with open(STRAVA_STATE_PATH) as f:
                state = json.load(f)
        return {
            "_mode": "env",
            "client_id": env_id,
            "client_secret": os.environ.get("STRAVA_CLIENT_SECRET", ""),
            "refresh_token": state.get("refresh_token") or os.environ.get("STRAVA_REFRESH_TOKEN", ""),
        }
    if not os.path.exists(CONFIG_PATH):
        raise SystemExit(
            f"Missing config.json at {CONFIG_PATH}\n"
            "Copy config.example.json to config.json and fill in your Strava app credentials."
        )
    with open(CONFIG_PATH) as f:
        cfg = json.load(f)
    cfg["_mode"] = "file"
    return cfg


def save_config(config):
    if config.get("_mode") == "env":
        os.makedirs(DATA_DIR, exist_ok=True)
        with open(STRAVA_STATE_PATH, "w") as f:
            json.dump({"refresh_token": config.get("refresh_token", "")}, f, indent=2)
            f.write("\n")
        return
    out = {k: v for k, v in config.items() if not k.startswith("_")}
    with open(CONFIG_PATH, "w") as f:
        json.dump(out, f, indent=2)
        f.write("\n")


def load_activities():
    """Return {id: activity} dict of the full merged history."""
    if not os.path.exists(ACTIVITIES_PATH):
        return {}
    with open(ACTIVITIES_PATH) as f:
        raw = json.load(f)
    return {str(a["id"]): a for a in raw.get("activities", [])}


def save_activities(by_id):
    activities = sorted(by_id.values(), key=lambda a: a.get("start_date", ""), reverse=True)
    payload = {"count": len(activities), "activities": activities}
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(ACTIVITIES_PATH, "w") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")


def load_plan():
    if not os.path.exists(PLAN_PATH):
        return None
    with open(PLAN_PATH) as f:
        return json.load(f)


ATHLETE_PATH = os.path.join(DATA_DIR, "athlete.json")


def load_athlete():
    if not os.path.exists(ATHLETE_PATH):
        return None
    with open(ATHLETE_PATH) as f:
        return json.load(f)


def regen_data_js(synced_at=None):
    """Bundle activities + plan into data/data.js so dashboard.html works over file://."""
    from datetime import datetime, timezone

    acts = load_activities()
    activities = sorted(acts.values(), key=lambda a: a.get("start_date", ""), reverse=True)
    payload = {
        "synced_at": synced_at or datetime.now(timezone.utc).isoformat(),
        "activities": activities,
        "plan": load_plan(),
        "athlete": load_athlete(),
    }
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(DATA_JS_PATH, "w") as f:
        f.write("// Generated file - do not edit. Regenerated by strava_sync.py / build_plan.py\n")
        f.write("window.DASHBOARD_DATA = ")
        json.dump(payload, f, indent=2)
        f.write(";\n")
    return len(activities)
